title: Business Analytics
description: Mark Soro personal modules and project website for
Business Analytics Nanodegree from Udacity. Awarded after completing the challenge course.
show_downloads: false
google_analytics: G-FGD1M93BQ2
theme: jekyll-theme-cayman
plugins:
  - jemoji
