title: Business Analytics
description: Mark Soro projects website and modules for Business Analytics Nanodegree.
show_downloads: false
google_analytics: G-FGD1M93BQ2
theme: jekyll-theme-cayman
plugins:
  - jemoji
  - jekyll-seo-tag
