title: Business Analytics
description: My personal modules and projects site for Business Analytics Nanodegree awarded by Udacity after completing the challenge course.
show_downloads: false
google_analytics: G-FGD1M93BQ2
theme: jekyll-theme-cayman
plugins:
  - jemoji
